### ISSUE TITLE
Queens, Multi-Sport Schedule

### ISSUE THREAD

**Issue by Aubron** [Aubron/scoreshots-templates#25] opened 2017-08-02 15:21 UTC
### Requested by:
Queens University
### Due Date:
2017-08-02

## Template Description:
Original message from Danielle Nicosia of Queens enclosed below:

> I was wondering if there was a way to get a template made up that would allow us to put multiple sports schedules with a cut out of a player from that sport on one template.  Also, if it could be made in poster size that would be fantastic!

She's been informed that what we can create right now is rectangular stuff that she could resize to poster dimensions later when that functionality is released.

## Dynamic Considerations:
N/A

## Additional Materials
Client example image, except poster-sized.

![dgetanpxkaenl8o jpg-large 1](https://user-images.githubusercontent.com/26412274/28881070-f24cd1ba-7774-11e7-938b-4e19d7ebd8b9.jpeg)

**Comment by ValentineRain** [comment] 2017-08-02 15:23
Double posted. Closing.

**Comment by Aubron** [comment] 2017-08-02 15:41
Meeting 8/2: Ask client if they're cool with 2-3 sports, horizontal layout, how many cutouts.

**Comment by ValentineRain** [comment] 2017-08-07 13:53
This is from the client, all of the information we needed is accounted for.

> Good Morning Val,
> 
> Sorry I am just getting back to you.  A horizontal template is perfectly fine!
> 
> If it's possible to have more than 3 teams that would be great but if not thats totally fine! As for the cut out spaces it's fine if there are only a few and I can just add more in!
> 
> Thanks,
> Dani

Taggin @adavila17 to work his magic.

**Comment by adavila17** [comment] 2017-08-07 19:08
Done leave me alone, like forever!

![ss_multisport_schedule](https://user-images.githubusercontent.com/26416133/29041807-471bd5c2-7b82-11e7-9b0b-75358efae4ac.jpg)

**Comment by ValentineRain** [comment] 2017-08-08 16:22
Remove cross country.
Change subheadline to indicate home fall games.
Val to research number of home games per season: FSU. 

Dynamic options requested via dropdown:
- 2 Sports W/ Cutouts
- 2 Sports W/O Cutouts
- 3 Sports W/ Cutouts
- 3 Sports W/O Cutouts

(Separately task single sport home and away schedule which can be used for any sport.)

**Comment by adavila17** [comment] 2017-08-09 18:00
![ss_multisport_schedule](https://user-images.githubusercontent.com/26416133/29135510-5d3bb6d8-7d08-11e7-9975-aebc74df4dab.jpg)

![ss_multisport_schedule_3wco](https://user-images.githubusercontent.com/26416133/29135509-5d36cace-7d08-11e7-96b6-14eb21af2553.jpg)

![ss_multisport_schedule 2](https://user-images.githubusercontent.com/26416133/29136248-aaf64c88-7d0a-11e7-81c0-e4d289b1b8ab.jpg)

![ss_multisport_schedule 2 wco](https://user-images.githubusercontent.com/26416133/29136379-1475f78a-7d0b-11e7-89ee-6af123aff99d.jpg)

**Comment by adavila17** [comment] 2017-08-16 12:21
Ready for dev template IDs are 628 & 629.

Dynamic options requested via drop-down labeled "Number of Sports":

**629 is the 2 team version**
2 Sports 
2 Sports W/ Cutout in front

**628 is the 3 team version**
3 Sports 
3 Sports W/ Cutout in front

If "W/ Cutout in front" is chosen move "Player Image 2" in template ID 629 in front of tear which is labeled "overlay". Also, move "Sponsor Logos 1-3" underneath Your Logo in the top left corner.

If "W/ Cutout in front" is chosen move "Player Image 3" in template ID 628 in front of tear which is labeled "overlay". Also, move "Sponsor Logos 1-3" underneath Your Logo in the top left corner.

**Comment by kelvin-im** [comment] 2017-08-16 12:42
I'll work on this one.

**Comment by adavila17** [comment] 2017-08-16 16:12
media relations

**Comment by kelvin-im** [comment] 2017-08-17 19:42
This has been dynamicized. One thing to note, the three logos does overlap the tear image and the text underneath. The logos may need to be decreased on the Admin section side. Give it a test and let me know @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/244

**Comment by ValentineRain** [comment] 2017-08-17 21:43
Starting on this now.

**Comment by ValentineRain** [comment] 2017-08-17 21:55
I'm a little confused about the dropdown. Admittedly, this may be my fault for not thinking of this ahead of time, but "Number of Sports" isn't quite the right name for it now that this template has been split into two. The 3-sport variant will _always_ have three sports. Technically we're just choosing "Cutouts" or "No Cutouts".

I'm also not really sure I understand our decision to make this a dynamic template in the first place now that we're splitting it into two templates. The user always had the option to just not add cutouts they don't want. There are some minor differences in logo placement, admittedly, but the dropdown itself made a lot more sense when this was all in one template. I'm not saying we should return to that, necessarily, just that maybe we don't need the dynamic treatment for these after all?

If we do decide to keep pushing down this path, though, the player cutouts in 628 (and probably its sister) do not hide if the dropdown is returned to "no cutout". Which does defeat the purpose of it a little.

![untitled 5](https://user-images.githubusercontent.com/26412274/29435151-e0b201b8-8373-11e7-9259-a7864406822f.png)

Finally, the title fields in the preview image are semi-transparent, but initialize as solid. There's nothing wrong with that, it still looks good, but is that something we meant to set by default and forgot?

**Comment by ValentineRain** [comment] 2017-08-17 21:56
Hey, so, actually, I think we might have overcomplicated this task bit. I'd like to pull back on this just a tad, and meet with @adavila17 and maybe @Aubron on where these are going. It's entirely possible that I misunderstood something in this process and I want to make sure I'm not the blocking issue.

**Comment by adavila17** [comment] 2017-08-18 14:16
So there will never be any state in which cuts out will not be needed. The layer order of the cuts will change based on if they want a cut out in front of the tear or not.

**Comment by ValentineRain** [comment] 2017-08-18 14:20
That makes a little bit more sense. So the "Number of Games" dropdown is not controlling whether cutouts are visible, either, but their layer?

**Comment by adavila17** [comment] 2017-08-18 18:50
"Number of Sports" because games are nullified since the template can be used for multiple sports.

**Comment by ValentineRain** [comment] 2017-08-21 18:30
I'm probably the limiting factor to this so I'm adding it to our review, so I can have it explained to me and test it properly.

**Comment by Aubron** [comment] 2017-08-21 19:24
Adam to add through-dates for series.
Condense this to 1 template, with the following options (maybe renamed)

2- Sport Cutout in Front
2- Sport Cutout Behind
3 - Sport Cutout in Front
3 - Sport Cutout Behind

Val will fix names shortly.

**Comment by Aubron** [comment] 2017-08-21 19:27
Val also to add bug report for logos that are too tall for drop zones.

**Comment by ValentineRain** [comment] 2017-08-21 19:45
Thanks for the info @kelvin-im , here's what we're doing with this.

Both template styles will be condensed into a single template, with the same configurations. There will be four states (the dropdown can still be named "Number of Sports" since we're combining them, I guess).

- 2 Sports, Cutout in Front
- 2 Sports, Cutout Behind
- 3 Sports, Cutout in Front
- 3 Sports, Cutout Behind

If player cutouts are removed from a state, they should be hidden from the canvas if they've already been added, until the user returns to a state capable of displaying them.

I still think the better solution in the future is to give the user layering controls but we can revisit that for ScoreShots 3.0. I will be making a separate bug report shortly (eventually) about the logo issue you noted, so don't worry about it for now. It looks like it might be systemic of a wider problem.

If you have any questions, let @adavila17 or I know. Sorry for the redo!

**Comment by kelvin-im** [comment] 2017-08-22 12:52
Working on this now.

**Comment by kelvin-im** [comment] 2017-08-23 15:40
Alright, both template styles are now condensed into one template. I've used template 628 as the base. Give it another test @ValentineRain, when you get the chance.

**Comment by kelvin-im** [comment] 2017-08-23 15:43
@adavila17, I had to make a small change in the layers for template 628/629. `sport 1opponents` I had to change to `sport 1 opponents` in the Admin section. This will need the change for LIVE.

**Comment by ValentineRain** [comment] 2017-08-23 17:53
Thanks for the note, @kelvin-im , we'll follow up on that after the merge.
Testing this now.

**Comment by ValentineRain** [comment] 2017-08-23 19:08
I'm having trouble switching between the options in the dropdown. Nothing is changing, and this is in the console log in Chrome:

![error](https://user-images.githubusercontent.com/26412274/29633485-67976048-8814-11e7-925e-beaaefe67f00.png)

Firefox looks a little different:

![error2](https://user-images.githubusercontent.com/26412274/29633574-ba7f0edc-8814-11e7-8c7e-e1f1eadb806b.png)

I'm still using [this PR](https://github.com/Aubron/scoreshots/pull/244), and template 628 like noted above. Are those the correct settings or is the cause of this one actually my fat stupid face?

**Comment by ValentineRain** [comment] 2017-08-23 19:24
The fix posted above fixed it and this template is good to go! 
Thanks for all your work on this guys, I know this one went back and forth a lot.

**Comment by Aubron** [comment] 2017-08-28 19:01
Merged. Preview images?

**Comment by ValentineRain** [comment] 2017-08-28 19:12
@adavila17 if I could get this one prioritized please so I can deliver it to our incredibly patient client.

**Comment by adavila17** [comment] 2017-08-28 19:55
preview added

**Closed** 2017-08-28 20:16 UTC
Labels: Priority: Low, Status: Needs Finalization / Preview Image
