### ISSUE TITLE
Template ID: 381 Football

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#67] opened 2017-09-11 11:27 UTC
Possession Time Circle is not starting in the right location it should start at the vertical top center, not the horizontal center right.

![slack-imgs](https://user-images.githubusercontent.com/26416133/30272465-a49ae6d8-96c2-11e7-8b7e-aeff38a4e593.png)

**Comment by kelvin-im** [comment] 2017-09-12 14:04
Taking a look at this one.

**Comment by kelvin-im** [comment] 2017-09-12 14:44
Alright, should be fixed now. Needed to revise the start and end points for the graph. Ready for review/testing @ValentineRain.

PR: https://github.com/Aubron/scoreshots/pull/280

**Comment by ValentineRain** [comment] 2017-09-12 18:24
This looks good to go, @adavila17 reviewed it and confirmed this is as intended. Good job!

**Comment by ValentineRain** [comment] 2017-09-12 18:24
Will close this once it's been merged.

**Comment by adavila17** [comment] 2017-09-14 17:01
bc it's a template @ValentineRain  and this is where templates/template bugs should go.

**Comment by ValentineRain** [comment] 2017-09-14 18:58
This will probably remain open until next week; it's too late to merge things this week.

**Comment by Aubron** [comment] 2017-09-18 17:05
This is going to live.

**Closed by Aubron** 2017-09-18 17:05 UTC
Labels: Priority: High, Status: Needs Finalization / Preview Image
