### ISSUE TITLE
Pistons - Quote of the Night Template

### ISSUE THREAD

**Issue by marissab1** [Aubron/scoreshots-templates#157] opened 2017-11-30 16:25 UTC
## Requested by:

Detroit Pistons, Douglas Wernert
Private, Due December 4th
2 of 6 Prepaid

## Template Description:

![quote-template_wired_1920x1080](https://user-images.githubusercontent.com/31700405/33441631-22a76816-d5c1-11e7-97c3-aeba4b21276b.jpg)

[This is a link to the PSD file](https://drive.google.com/a/imsports.com/file/d/1HEwhFKoNNmZeZZ5avpbCtcHzvrDeOPm7/view?usp=sharing)

**Comment by adavila17** [comment] 2017-11-30 19:48
@ValentineRain test temp ID: 739

**Comment by ValentineRain** [comment] 2017-12-01 19:56
This template works as intended. Two notes;

1. The transparency for our version is not as dramatic as the one in the preview image they asked for (note in the image below how it's mostly opaque by the time you reach the quotation marks. We might want to make that more pronounced if there isn't a reason we can't.

2. The default copy is sassy and I like that, but probably not appropriate for a brand new partner. Can we make it more generic? I'd be find delivering something like this to a regular.

![copy](https://user-images.githubusercontent.com/26412274/33500707-c2cb6b62-d6a7-11e7-86d0-ce964be06ed4.png)

Take a look at those two items and then we can go ahead and ship it.

**Comment by adavila17** [comment] 2017-12-02 00:34
odd that second line was changed before i asked you to test to and another line. oh well must have forgotten to save. It's done also the opacity changes based on the background image.

adding preview category needs to be added to client and they also need to be informed the template is ready.

**Comment by ValentineRain** [comment] 2017-12-03 03:32
I'm going to go ahead and set up their category.
If @lisajohnson11 can let them know where to find it between now and EOD Monday, I'll go ahead and close this task!

Thanks Adam.

**Comment by ValentineRain** [comment] 2017-12-03 03:36
Hey actually, I don't know what's wrong with me, I've got their contact informaiton. I'll just go ahead and let them know, @lisajohnson11 !

**Closed** 2017-12-03 03:40 UTC
Labels: Priority: High, Status: Needs Finalization / Preview Image
